apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    component: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      component: traefik
  template:
    metadata:
      labels:
        component: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.1
          args:
            #- --api.insecure
            - --api.dashboard=true
            - --metrics=true
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
            - --metrics.prometheus=true
            - --entrypoints.metrics.address=:8888
            - --metrics.prometheus.entryPoint=metrics
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
            - name: metrics
              containerPort: 8888
